{ pkgs, lib ? pkgs.lib }:
let
  zones = import ./zones.nix;

  quote = builtins.toJSON;
  concat = lib.concatStringsSep;
  ttlArg = record: if record ? ttl && record.ttl != null then ", TTL(${toString record.ttl})" else "";
  absoluteTarget = domain: target:
    if target == "@" then "${domain}." else if lib.hasSuffix "." target then target else "${target}.";

  require = record: field:
    if builtins.hasAttr field record then
      builtins.getAttr field record
    else
      throw "dns/render.nix: missing field '${field}' for ${record.type} record ${record.name}";

  renderRecord = domain: record:
    let
      name = quote record.name;
      ttl = ttlArg record;
      get = require record;
    in
    if record.type == "A" then
      "A(${name}, ${quote (get "value")}${ttl})"
    else if record.type == "AAAA" then
      "AAAA(${name}, ${quote (get "value")}${ttl})"
    else if record.type == "CNAME" then
      "CNAME(${name}, ${quote (absoluteTarget domain (get "target"))}${ttl})"
    else if record.type == "MX" then
      "MX(${name}, ${toString (get "priority")}, ${quote (absoluteTarget domain (get "target"))}${ttl})"
    else if record.type == "NS" then
      "NS(${name}, ${quote (absoluteTarget domain (get "target"))}${ttl})"
    else if record.type == "SRV" then
      "SRV(${name}, ${toString (get "priority")}, ${toString (get "weight")}, ${toString (get "port")}, ${quote (absoluteTarget domain (get "target"))}${ttl})"
    else if record.type == "TXT" then
      "TXT(${name}, ${quote (get "value")}${ttl})"
    else if record.type == "CAA" then
      "CAA(${name}, ${toString (get "flags")}, ${quote (get "tag")}, ${quote (get "value")}${ttl})"
    else
      throw "dns/render.nix: unsupported record type ${record.type} in ${record.name}";

  renderZone = domain: zone:
    let
      nameserverTtl = lib.optional (zone ? nameserverTtl && zone.nameserverTtl != null)
        "NAMESERVER_TTL(${toString zone.nameserverTtl})";
      nameservers = map (ns: "NAMESERVER(${quote ns})") (zone.nameservers or [ ]);
      records = map (renderRecord domain) (zone.records or [ ]);
      bodyItems = [ "DnsProvider(DSP_DIGITALOCEAN)" ] ++ nameserverTtl ++ nameservers ++ records;
      body = concat ",\n" (map (line: "  ${line}") bodyItems);
    in
    ''
      D(${quote domain}, REG_NONE,
      ${body}
      );
    '';
in
pkgs.writeText "dnsconfig.js" ''
  // Generated from dns/zones.nix. Do not edit this file directly.
  var REG_NONE = NewRegistrar("none");
  var DSP_DIGITALOCEAN = NewDnsProvider("digitalocean");

  ${concat "\n" (lib.mapAttrsToList renderZone zones)}
''
