# Generated by .gitea/scripts/import-digitalocean-dns.py
# Review carefully before merging; this is intended as a bootstrap snapshot.
#
# This bootstrap snapshot has been cleaned up into hand-maintained Nix. A future
# import run will flatten it back out again.
let
  digitalOceanNameservers = [
    "ns1.digitalocean.com."
    "ns2.digitalocean.com."
    "ns3.digitalocean.com."
  ];

  publicIps = {
    ponyo = "147.135.114.130";
    ponyoIPv6 = "2604:2dc0:101:200::1092";
  };

  tailscaleIps = {
    ponyo = "100.76.85.13";
    fry = "100.117.73.96";
    s0 = "100.112.73.53";
  };

  hosts = {
    mail = "mail.neet.dev";
    ponyo = "ponyo.neet.dev";
    collaboraPonyo = "collabora.ponyo.neet.dev";
    whiteboardPonyo = "whiteboard.ponyo.neet.dev";
  };

  absoluteHosts = {
    mail = "mail.neet.dev.";
    ponyo = "ponyo.neet.dev.";
    gitPonyo = "git.ponyo.neet.dev.";
    ircPonyo = "irc.ponyo.neet.dev.";
    statusPonyo = "status.ponyo.neet.dev.";
  };

  txt = {
    spf = "\"v=spf1 include:mailgun.org mx -all\"";
    dmarcNone = "\"v=DMARC1; p=none\"";
    rizonVhost = "\"rizon_vhost=Googlebot,Zuckerberg,dailybot\"";
  };

  dkim = {
    "bsd.ninja" = {
      mail = "\"v=DKIM1; k=rsa; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAq8g5CJ7Tub4CuD53ychUrSyo8xw2YyVDdpccEacevda4DAXbrLadK8VNPG1qMpkec2oENihC2gjwTDLJvPhhlelM0jZyq4AJHVTEFHJuNejb+Qxr8DHwL5KusH+jh54E6O68p8A5uvMojUuuaSTrc2JWAjndA1AphhoC18G8VxkLwdT/l3sgSuSArdklIWGVKRgTe1LM0VIxxTNkGtVSuVnk1Y4enFAhUG+llCV4GN76jyzrGQVkr9BdMQ3AV3t0REbJTT615nk0YPIimSvXW6qBj1MT4+2GE210vPvfbaILu1RHKsxt9JJKZ6A6DDh965e0Jshhf7J0/FAmgrIQLwIDAQAB\"";
      mx = "\"k=rsa; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtFGf6jIhKkX7CJDoqj1ABa6PYXj4adiW/szo5uvzfTb2/aWg66QfD3qyTHndMhNvpGecnTA9kYevS0MqdFu3eTrRpefw6itNtrJivSUxZqx++SqIsKv8XgLBuStylvceONhzCaCB6zfZxZLe47rXGqrLFj2RlHJctVrQ3Vmgn2yc7/l5dAw+ORulrgaeRLhFeQIDv1ZWQ0wLdn9BEXixe0cy3PRx4nWdiQ5Pulsw9qUXgh8Lel2kkg/KObTe2Y/UlEAGhg22Oa3PkMoC+TtmsE/eLRXrBhMLgcETWWRZnn73v30Fg78abH8WXRIMC98inMTXIF2E1zb3WMgCQVIBzwIDAQAB\"";
    };
    "bsd.rocks" = {
      mail = "\"v=DKIM1; k=rsa; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAoXl9WaBd5oOOm5tmfVhM1SD9GCwQs2DnOx6v0BelX7eskaIik6t3n+xdtfaYB/N0VYb9eC767If9ICh0kwryndHWsqdpi/xzuaeGJkLD0/kMVgaNF3bQpvKryh9EJk0UIMrFvPTxWTBub6jhmtwo/q/rwRZEeVv6xawPNEB71uNaICkN1Cy3M/3NSD58rGk4u3+W9HM57P5c81Rp1ZAwy6FGTt8ZAS2DNb1zb8gEnzZyICC4YdOMkZj//v6f1OPfm6BGYS+UeLwKicVPl8ovPEiE2HyMSF3Cs7y+4WRolg3Ec/WzGKNPE8EyyeGtqxRnkjM2t8DJhT+qaP8KlKhqBwIDAQAB\"";
      mx = "\"k=rsa; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAv+ewzuWyh+4ZABGu/1jQMvfkbctJpv+qkCjyWXb997ZOxxjt9hbXWj2/5rHvpAxfMTLkMiclo1SyrCAboHrIrOqY3fRL2rj/EQM9PkOuumLAPji/alponDMdlNBIs2rUOYOSaBkc46Jz0Ke9FuSTnCqJh51ZKENd1kJbgJuRGTI1UpwZHZ0TF1m7DvtQuRdHaNA9FklIRGlTcRTmxSAApG7EJX/dyvJhHwJJGvc80ssxRjR7BBBqk9iKC+ENsuje9LERyCZdSNriqvJTB6LPt7A4gUPU1tc/ot0gLbDgtMFsjj2LerQMuHsn0kgNpJ777bwic7Ct+oJa/ds+1Rz4swIDAQAB\"";
    };
    "neet.cloud" = {
      mail = "\"v=DKIM1; k=rsa; s=email; p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQC+BqOno9bpvPUwy8YDq/A7NGY3WQk4ia4JVKxdEKzkEB5JbkhBPpkbLnkd+bg7ZtII+tS03dAaVdC1xD8w/+fzZg41a1SM5c37Q4UEISuHt9gitYzTvwIvLpeWw5EPKkHMVuJHhNfsxoi0cdD4yj3mj5Rawtqiyv74L5wRreWprwIDAQAB\"";
      pic = "\"k=rsa; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwSqJTFMGKSh9eloD55B8Cte0ZDadZPLozjC5VFbzbCP+WzGFW1bq4/52T3woG7a6b/Br8fJq0rQqbzZP5/q3qW8AifUA9Z6SoUoTc1LS6Csv17+ON5mDJmSJEM/FWsh/Eq8BStsfF/LJCyQt9SPDunAg5aFtSUVpVfALsB36GimGoNEs6dhArUSXBIkkEmrSjQ4D9N5iB2CwMfVbQpoTk0d06XFVAYoWWjIsuLcUUrB+Yw0y8E7JRIHTSqVAnPbwmt0F2tWaNKMISHXGYlr4DaDIvR0jVDV7E+EwJLTgLPG9P3uXPrTvnnheX+Oa1XnuC3xRGrgWhIWM6bZniBLqbwIDAQAB\"";
    };
    "neet.dev" = {
      krs = "\"k=rsa; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsu2Ev3WCXIMl4YefkeyurRLXlByTrsXKcREtXxHmFXxwwFx4V05o8aKiFFTgBjx1Q4HTVXpKJucUQaIftWfbm55WLRRpENDLnkmyqjaSLrijpE6Ytg46cziUgFrOtFq1qehns5tsUeo8CQ/J9a2zHK20iox51LMxQ7e0WZzUWfZWa/PeIwOVlrrAFvl0f7w8EHjUzEuAl+IYWvtFh4QPXKIxqwzQPIB9jEaRHUYFlK9LSMrfYPl9k0OjF/1xHMjzUkFZgcgfAoj4wtTDqYMXLV+bfJPbxLghSBZ7hshx3zqgqmMdOz6XdNSXI3/Pgd9p7clEdTki6ZEssXlJyS6LxwIDAQAB\"";
      mail = "\"v=DKIM1; k=rsa; s=email; p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDnkeYFM9fTlRBihTQpPW+us7jBuFofKgvORRxm0dtyaumg4Z6ZWlol1DKZE2LJ196agh5agfkXkVm97x/LrZQRvS0822y42F86STee4+ZWdt9DV6j3zmucu1lqe70m0lB5PnnEqFi2r4SEpsii1ti+p38RAjeewQoLp/5A+7A59QIDAQAB\"";
    };
    "neet.space" = {
      mail = "\"v=DKIM1; k=rsa; s=email; p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCfsgdL8ngVtMFLdkTxaKfcO4zl2tWye9Dc6goDcKaGWadp4G/e4282fQ+jqG8aFYpGUrdq1yH3LhowA/mQuCr/WRWxsRatB4D0tTcQUSYAzduOuFWKfO029MdRxEGxt38c+lQjeck5+ScLTMo4CFhlaBT8syqcjLu4ORdwMCREmwIDAQAB\"";
      smtp = "\"k=rsa; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAoI62Pb0vhm72bd67mZmNH+hwImJaHWirYO2iEedt4l2ESFVZ+3OZ5L33MnN/HT0h7WI4jSvG8lJz0y0WhXCA8TLrk5exa4kLz4bJEbW37yRO8FNgtU5CPQFtrXU94Dg6u+8DJJ9V+xFc4ufsvDgMffH9fRHXll9rDsrW2ae0+MhPSqIKMLWp/v108zXyDPBPNw5bPBxg48AQBv0y+21YAhFkAUdSm46JVZXMTEBzz/iLr3wvnX/QadnXn+0fUIGGvLT9dUQFZ6uYpRGOqRvIMtwKxdoCUyqLIMff5WB5yYhyVDftKrPAFwry93RT55U7zCnrBBznCefKeeQ+vjkTQQIDAQAB\"";
    };
    "runyan.org" = {
      mail = "\"v=DKIM1; k=rsa; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAt1N9lHlFuMHABaDrJJkAiyhbpH5WhXd2s3bJ+UF1CTqOYGr3dtXwnxEZCjXhv5QkGAbI60cD+YjNejRcMByn+R6FUhZp83eLxlPJej//N+oP5JSNp2irJEm0Qzx3Te7Qx9rtyrIFfNnpMSwGblmBVaONR7lbpJEYtoY34y5THlBA2DA9aHS48ybAfnw69LFev34Yr0i8ozIssbhsSqSsZOEJifQk5I0GQoskBCdfxQ4NfP6iuuj9HX8tkYGSdmdO3LaVWh/tRNAX451RHSLMhnQMHsGWBLJoA1eHBplQqYXpA2gRGwCcRDQZ5/D7Y3+8mvp2YgBlKG1Pav1QLrmPTwIDAQAB\"";
      smtp = "\"k=rsa; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuAK0ydDLErw0gzn3bmyIU3urTrNuIkCWrmfl1DXWItmB8jM517uFERhOtoocnbhO4Y1+FvxU+YUhlZKfUccKEqtMjc/dROXOHX2nDRtchd1ss/fUOiwSOlRrZZexdunPs78mibrH6yUVyktGq+is6zpxNpyFbJE9LjScYDWw+reR+7oMrmPQnX3MJ15B1yXHuwkLvz2OWr7Kz2P6MzzlLNMT4haCFCBkcYwdLFGFNtNO5Lw33Azx8HmGnEd7BjT8Z/ZVRgv8YLZcczTCkdwbrFtDkv06xOr/5NXnYQKoUxS1jSOkGwkNHnYlJwedBYNDAkbUAGcGQ4SadUxQm6xpXwIDAQAB\"";
    };
    "runyan.rocks" = {
      k1 = "\"k=rsa; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAolNaBvjQPi92OJev5FIL2gSXPuDW3IFoKoUo+eksfZstT3F5LDxhqP2NpjiJQ02BM2fFz8BUYIknNC1saHO65Wc6htEnFXAwvpfamm8XXpfysBEjGDOnxpepGrN065Nlyz5XYPapQFC02YLU5l4+A/KJTDPShHMKs32ZCKmZ2YboeWsEt4TQK0mLH3I+9DZ/59yTr2u/mxzq3scMTHtFQXm17StFumVGZYsfuZIkQCBN64F+okxiS9X9FL0FF0YzktTTiz0H87XZG1IK6MF4GBgW0Jz9A4fWPUqrJFBC6FcPOJLw47o555FqcysqFal3QQATPwuxDKHfkWrcxI3AkQIDAQAB\"";
      mail = "\"v=DKIM1; k=rsa; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA5dDZZfWWJ9C0HB9LXZT86yf8oo5x6wnTUECsbFduvozPBiwR2Li63XXr0WTx4BbjHTghe5z+6EyxMgJngWHUS+q9gkAFaJVm+jbuP7PvVkHt9/RKenPs6Sxyn3lqk263cxJ18Z1aWICgovBDuaXiC6FWv2z2P7A1V6VA/WbRGZA3QGRTK3qF9IN+WBaqUKIp0ZcLVdhMNeGmAq+Ot4+pqu8GL0M8S7E+AmUriuCcR/BCwP1iWdtu2ryq0iR3cdT+0nBuSwiueWnJxuAZbrzq0mIw8g9LVaeGFmzvhbKA5zIWSDiGRE3oiq2CQ3iWpuayb5Iy6BexfvLJadchREzd6QIDAQAB\"";
    };
    "tar.ninja" = {
      mail = "\"v=DKIM1; k=rsa; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA43EOZqcsaNWFTokyXZjniwiHqNovuXjjpklkCFSw0DiqNE1ZAI+9khO1cWDzEJLESvLkiO+AdeL+3BluEc8mtGcEa7CVzPsRQxQ6ABidyCtL5asDHtACmUz1wZG+5tbECXLmbuKafVVA7wY3FTJqwwLMk7Dm2njmXdD5YRxDFvnR1eQeKgPxzmBc7yhd+RsZElVvAYdGf8llvqsdRitV/oPrxCiNqQMvS/EdiAhegNyTBUtvSnv7HCo6A32V6/twOMjTMlqEq8zUOiJHTkH6jBLkRFcY7U0EonSharz7FR9iIKcrcxm6PggDRXYgErQQfv1LmAWlKOD7SOFX9S0PAwIDAQAB\"";
      mailo = "\"k=rsa; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAp/lXoClCYyegOhvQXiKv/WWYH9M2k6l4/UrfprAyZ+waeEDzWb2bNjFmlZJkxq0VTys8t2kag1HppS7I/+FZWKgWEAsv8mhCeEyDUQOR98Gj4oIefh7Y+8ql3++D/tKKzPJWIFhOlo5TcETx+jL9hm1G45OvDmTYgbju/tdBq/yq0FQDJ+0kdWzFtYPoPSmLrcik2C17CkyMD33wiJmOCxKwddesscNHPLr095rEJ2XXiYJg9rHJhlxYmu3u09SuwDuk/UT1Y8DhvZNHRpMv+vsS+xCFpJU9kNSNtUU40XSxMi3HWCUaetTJlZQodr7d+nNqLF/PLjJvS1Lc/d1g1wIDAQAB\"";
    };
    "thunderhex.com" = {
      k1 = "\"k=rsa; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAohWXVoGp9x1f7TFfxdp4p6VwANxvsrZGZmq4Tfuib9us+ADzePU9rQFRnWjqvteu/U800KMP/7+krQSvb2x9MpVmHs+T4nbRwGowVAmgVJR4LhaipTIDTVDqXhg5/1NVeRr6AFfqOsw7jI2ubinGqiu3cmXjWHryvJEVF63Iio5ckL9zO4A23Av1YeABDh8bzDs7HQ6l2yhUMsHy4vaZ9AijALWUg2NilLMovXkFy32qhLNza+vjJ9wE7Q+3H/Tb3L5JRgKyOAYye3o8mwnsXTh/I/nW+AxK5ixANg+nC4hNeI3fuXaL7vEqgNzxoRyF5H90FjHfN707XR2YvQyc/wIDAQAB\"";
      mail = "\"v=DKIM1; k=rsa; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA3trwBpGv/mpss4Ep2fXpGlZju4zahfaBF2pFEmqZcgdvPeYiDPKHyRUV8BZ+socO1Qj0M6Rwn09NRBrWksVGfIQdP3nT/DU+Le3zEIT0Tbjdx1Ag//E3Z7gnreEoUkcF18Lsghitlnd0XX1tnLmmta09tpgHi06AZyFjsGzN0mBOGkpoTAKd991VT4FyR6p2YvvWBhmgptAYlWJAIM44v+zV5GXUH37mMBwGGAk8/N+CWiuqUsJriyv/qOBb/rZgUPw/bgJSwJ4H0eU3btnZocv5D3d3iKVCl8YfmW7JM6Fev5S+JAOYufIiyvQisR6Hm9zm2GVQZDdiP2uHbZvu4wIDAQAB\"";
    };
  };

  mkA = name: value: ttl: { inherit name value ttl; type = "A"; };
  mkAAAA = name: value: ttl: { inherit name value ttl; type = "AAAA"; };
  mkCNAME = name: target: ttl: { inherit name target ttl; type = "CNAME"; };
  mkMX = name: priority: target: ttl: { inherit name priority target ttl; type = "MX"; };
  mkTXT = name: value: ttl: { inherit name value ttl; type = "TXT"; };

  commonMailRecords = mailTarget: [
    (mkMX "@" 10 mailTarget 14400)
    (mkTXT "@" txt.spf 3600)
    (mkTXT "_dmarc" txt.dmarcNone 3600)
  ];

  zone = records: {
    nameservers = digitalOceanNameservers;
    nameserverTtl = 1800;
    inherit records;
  };
in
{
  "av1.zip" = zone (
    [
      (mkA "@" publicIps.ponyo 360)
      (mkAAAA "@" publicIps.ponyoIPv6 300)
    ]
    ++ commonMailRecords hosts.mail
  );

  "bsd.ninja" = zone (
    [
      (mkA "@" publicIps.ponyo 300)
      (mkAAAA "@" publicIps.ponyoIPv6 300)
    ]
    ++ commonMailRecords hosts.mail
    ++ [
      (mkTXT "mail._domainkey" dkim."bsd.ninja".mail 3600)
      (mkTXT "mx._domainkey" dkim."bsd.ninja".mx 3600)
    ]
  );

  "bsd.rocks" = zone (
    [
      (mkA "@" publicIps.ponyo 300)
      (mkAAAA "@" publicIps.ponyoIPv6 300)
    ]
    ++ commonMailRecords hosts.mail
    ++ [
      (mkTXT "mail._domainkey" dkim."bsd.rocks".mail 3600)
      (mkTXT "mx._domainkey" dkim."bsd.rocks".mx 3600)
    ]
  );

  "neet.cloud" = zone (
    [
      (mkA "@" publicIps.ponyo 300)
    ]
    ++ commonMailRecords hosts.mail
    ++ [
      (mkCNAME "cast" hosts.ponyo 3600)
      (mkCNAME "files" hosts.ponyo 3600)
      (mkTXT "mail._domainkey" dkim."neet.cloud".mail 3600)
      (mkTXT "pic._domainkey" dkim."neet.cloud".pic 3600)
    ]
  );

  "neet.dev" = zone [
    (mkA "*.fry" tailscaleIps.fry 3600)
    (mkA "*.ponyo" tailscaleIps.ponyo 3600)
    (mkA "*.s0" tailscaleIps.s0 3600)
    (mkA "@" publicIps.ponyo 300)
    (mkMX "@" 10 absoluteHosts.mail 14400)
    (mkTXT "@" txt.spf 3600)
    (mkTXT "_dmarc" txt.dmarcNone 3600)
    (mkA "fry" tailscaleIps.fry 3600)
    (mkCNAME "git" absoluteHosts.gitPonyo 3600)
    (mkCNAME "irc" absoluteHosts.ircPonyo 3600)
    (mkTXT "krs._domainkey" dkim."neet.dev".krs 3600)
    (mkA "mail" publicIps.ponyo 30)
    (mkTXT "mail._domainkey" dkim."neet.dev".mail 3600)
    (mkCNAME "ntfy" absoluteHosts.ponyo 3600)
    (mkCNAME "ponyo" "@" 3600)
    (mkA "s0" tailscaleIps.s0 3600)
    (mkCNAME "status" absoluteHosts.statusPonyo 3600)
    (mkCNAME "tmp" "@" 3600)
    (mkCNAME "unlock.ponyo" absoluteHosts.ponyo 3600)
  ];

  "neet.space" = zone [
    (mkA "@" tailscaleIps.ponyo 300)
    (mkMX "@" 10 hosts.mail 14400)
    (mkTXT "@" txt.rizonVhost 3600)
    (mkTXT "@" txt.spf 3600)
    (mkTXT "_dmarc" txt.dmarcNone 3600)
    (mkA "chat" tailscaleIps.ponyo 300)
    (mkTXT "mail._domainkey" dkim."neet.space".mail 3600)
    (mkTXT "smtp._domainkey" dkim."neet.space".smtp 3600)
    (mkCNAME "turn" "@" 3600)
  ];

  "runyan.org" = zone (
    [
      (mkA "@" tailscaleIps.ponyo 300)
    ]
    ++ commonMailRecords hosts.mail
    ++ [
      (mkCNAME "collabora" hosts.collaboraPonyo 3600)
      (mkTXT "mail._domainkey" dkim."runyan.org".mail 3600)
      (mkTXT "smtp._domainkey" dkim."runyan.org".smtp 3600)
      (mkCNAME "whiteboard" hosts.whiteboardPonyo 3600)
    ]
  );

  "runyan.rocks" = zone (
    [
      (mkA "@" publicIps.ponyo 300)
      (mkAAAA "@" publicIps.ponyoIPv6 300)
    ]
    ++ commonMailRecords hosts.mail
    ++ [
      (mkTXT "k1._domainkey" dkim."runyan.rocks".k1 3600)
      (mkTXT "mail._domainkey" dkim."runyan.rocks".mail 3600)
    ]
  );

  "tar.ninja" = zone (
    [
      (mkA "@" publicIps.ponyo 300)
      (mkAAAA "@" publicIps.ponyoIPv6 300)
    ]
    ++ commonMailRecords hosts.mail
    ++ [
      (mkTXT "mail._domainkey" dkim."tar.ninja".mail 3600)
      (mkTXT "mailo._domainkey" dkim."tar.ninja".mailo 3600)
    ]
  );

  "thunderhex.com" = zone (
    [
      (mkA "@" publicIps.ponyo 300)
      (mkAAAA "@" publicIps.ponyoIPv6 300)
    ]
    ++ commonMailRecords hosts.mail
    ++ [
      (mkTXT "k1._domainkey" dkim."thunderhex.com".k1 3600)
      (mkTXT "mail._domainkey" dkim."thunderhex.com".mail 3600)
    ]
  );

  "zstd.zip" = zone (
    [
      (mkA "@" publicIps.ponyo 300)
      (mkAAAA "@" publicIps.ponyoIPv6 300)
    ]
    ++ commonMailRecords hosts.mail
  );
}
