# Generated by .gitea/scripts/import-digitalocean-dns.py
# Review carefully before merging; this is intended as a bootstrap snapshot.
{
  "av1.zip" = {
    nameservers = [ "ns1.digitalocean.com." "ns2.digitalocean.com." "ns3.digitalocean.com." ];
    records = [
      { name = "@"; type = "A"; value = "147.135.114.130"; ttl = 360; }
      { name = "@"; type = "AAAA"; value = "2604:2dc0:101:200::1092"; ttl = 300; }
      { name = "@"; type = "MX"; priority = 10; target = "mail.neet.dev"; ttl = 14400; }
      { name = "@"; type = "TXT"; value = "\"v=spf1 include:mailgun.org mx -all\""; ttl = 3600; }
      { name = "_dmarc"; type = "TXT"; value = "\"v=DMARC1; p=none\""; ttl = 3600; }
    ];
  };
  "bsd.ninja" = {
    nameservers = [ "ns1.digitalocean.com." "ns2.digitalocean.com." "ns3.digitalocean.com." ];
    records = [
      { name = "@"; type = "A"; value = "147.135.114.130"; ttl = 300; }
      { name = "@"; type = "AAAA"; value = "2604:2dc0:101:200::1092"; ttl = 300; }
      { name = "@"; type = "MX"; priority = 10; target = "mail.neet.dev"; ttl = 14400; }
      { name = "@"; type = "TXT"; value = "\"v=spf1 include:mailgun.org mx -all\""; ttl = 3600; }
      { name = "_dmarc"; type = "TXT"; value = "\"v=DMARC1; p=none\""; ttl = 3600; }
      { name = "mail._domainkey"; type = "TXT"; value = "\"v=DKIM1; k=rsa; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAq8g5CJ7Tub4CuD53ychUrSyo8xw2YyVDdpccEacevda4DAXbrLadK8VNPG1qMpkec2oENihC2gjwTDLJvPhhlelM0jZyq4AJHVTEFHJuNejb+Qxr8DHwL5KusH+jh54E6O68p8A5uvMojUuuaSTrc2JWAjndA1AphhoC18G8VxkLwdT/l3sgSuSArdklIWGVKRgTe1LM0VIxxTNkGtVSuVnk1Y4enFAhUG+llCV4GN76jyzrGQVkr9BdMQ3AV3t0REbJTT615nk0YPIimSvXW6qBj1MT4+2GE210vPvfbaILu1RHKsxt9JJKZ6A6DDh965e0Jshhf7J0/FAmgrIQLwIDAQAB\""; ttl = 3600; }
      { name = "mx._domainkey"; type = "TXT"; value = "\"k=rsa; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtFGf6jIhKkX7CJDoqj1ABa6PYXj4adiW/szo5uvzfTb2/aWg66QfD3qyTHndMhNvpGecnTA9kYevS0MqdFu3eTrRpefw6itNtrJivSUxZqx++SqIsKv8XgLBuStylvceONhzCaCB6zfZxZLe47rXGqrLFj2RlHJctVrQ3Vmgn2yc7/l5dAw+ORulrgaeRLhFeQIDv1ZWQ0wLdn9BEXixe0cy3PRx4nWdiQ5Pulsw9qUXgh8Lel2kkg/KObTe2Y/UlEAGhg22Oa3PkMoC+TtmsE/eLRXrBhMLgcETWWRZnn73v30Fg78abH8WXRIMC98inMTXIF2E1zb3WMgCQVIBzwIDAQAB\""; ttl = 3600; }
    ];
  };
  "bsd.rocks" = {
    nameservers = [ "ns1.digitalocean.com." "ns2.digitalocean.com." "ns3.digitalocean.com." ];
    records = [
      { name = "@"; type = "A"; value = "147.135.114.130"; ttl = 300; }
      { name = "@"; type = "AAAA"; value = "2604:2dc0:101:200::1092"; ttl = 300; }
      { name = "@"; type = "MX"; priority = 10; target = "mail.neet.dev"; ttl = 14400; }
      { name = "@"; type = "TXT"; value = "\"v=spf1 include:mailgun.org mx -all\""; ttl = 3600; }
      { name = "_dmarc"; type = "TXT"; value = "\"v=DMARC1; p=none\""; ttl = 3600; }
      { name = "mail._domainkey"; type = "TXT"; value = "\"v=DKIM1; k=rsa; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAoXl9WaBd5oOOm5tmfVhM1SD9GCwQs2DnOx6v0BelX7eskaIik6t3n+xdtfaYB/N0VYb9eC767If9ICh0kwryndHWsqdpi/xzuaeGJkLD0/kMVgaNF3bQpvKryh9EJk0UIMrFvPTxWTBub6jhmtwo/q/rwRZEeVv6xawPNEB71uNaICkN1Cy3M/3NSD58rGk4u3+W9HM57P5c81Rp1ZAwy6FGTt8ZAS2DNb1zb8gEnzZyICC4YdOMkZj//v6f1OPfm6BGYS+UeLwKicVPl8ovPEiE2HyMSF3Cs7y+4WRolg3Ec/WzGKNPE8EyyeGtqxRnkjM2t8DJhT+qaP8KlKhqBwIDAQAB\""; ttl = 3600; }
      { name = "mx._domainkey"; type = "TXT"; value = "\"k=rsa; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAv+ewzuWyh+4ZABGu/1jQMvfkbctJpv+qkCjyWXb997ZOxxjt9hbXWj2/5rHvpAxfMTLkMiclo1SyrCAboHrIrOqY3fRL2rj/EQM9PkOuumLAPji/alponDMdlNBIs2rUOYOSaBkc46Jz0Ke9FuSTnCqJh51ZKENd1kJbgJuRGTI1UpwZHZ0TF1m7DvtQuRdHaNA9FklIRGlTcRTmxSAApG7EJX/dyvJhHwJJGvc80ssxRjR7BBBqk9iKC+ENsuje9LERyCZdSNriqvJTB6LPt7A4gUPU1tc/ot0gLbDgtMFsjj2LerQMuHsn0kgNpJ777bwic7Ct+oJa/ds+1Rz4swIDAQAB\""; ttl = 3600; }
    ];
  };
  "neet.cloud" = {
    nameservers = [ "ns1.digitalocean.com." "ns2.digitalocean.com." "ns3.digitalocean.com." ];
    records = [
      { name = "@"; type = "A"; value = "147.135.114.130"; ttl = 300; }
      { name = "@"; type = "MX"; priority = 10; target = "mail.neet.dev"; ttl = 14400; }
      { name = "@"; type = "TXT"; value = "\"v=spf1 include:mailgun.org mx -all\""; ttl = 3600; }
      { name = "_dmarc"; type = "TXT"; value = "\"v=DMARC1; p=none\""; ttl = 3600; }
      { name = "cast"; type = "CNAME"; target = "ponyo.neet.dev"; ttl = 3600; }
      { name = "files"; type = "CNAME"; target = "ponyo.neet.dev"; ttl = 3600; }
      { name = "mail._domainkey"; type = "TXT"; value = "\"v=DKIM1; k=rsa; s=email; p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQC+BqOno9bpvPUwy8YDq/A7NGY3WQk4ia4JVKxdEKzkEB5JbkhBPpkbLnkd+bg7ZtII+tS03dAaVdC1xD8w/+fzZg41a1SM5c37Q4UEISuHt9gitYzTvwIvLpeWw5EPKkHMVuJHhNfsxoi0cdD4yj3mj5Rawtqiyv74L5wRreWprwIDAQAB\""; ttl = 3600; }
      { name = "navidrome"; type = "CNAME"; target = "ponyo.neet.dev"; ttl = 3600; }
      { name = "pic._domainkey"; type = "TXT"; value = "\"k=rsa; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwSqJTFMGKSh9eloD55B8Cte0ZDadZPLozjC5VFbzbCP+WzGFW1bq4/52T3woG7a6b/Br8fJq0rQqbzZP5/q3qW8AifUA9Z6SoUoTc1LS6Csv17+ON5mDJmSJEM/FWsh/Eq8BStsfF/LJCyQt9SPDunAg5aFtSUVpVfALsB36GimGoNEs6dhArUSXBIkkEmrSjQ4D9N5iB2CwMfVbQpoTk0d06XFVAYoWWjIsuLcUUrB+Yw0y8E7JRIHTSqVAnPbwmt0F2tWaNKMISHXGYlr4DaDIvR0jVDV7E+EwJLTgLPG9P3uXPrTvnnheX+Oa1XnuC3xRGrgWhIWM6bZniBLqbwIDAQAB\""; ttl = 3600; }
    ];
  };
  "neet.dev" = {
    nameservers = [ "ns1.digitalocean.com." "ns2.digitalocean.com." "ns3.digitalocean.com." ];
    records = [
      { name = "*.fry"; type = "A"; value = "100.117.73.96"; ttl = 3600; }
      { name = "*.ponyo"; type = "A"; value = "100.76.85.13"; ttl = 3600; }
      { name = "*.s0"; type = "A"; value = "100.112.73.53"; ttl = 3600; }
      { name = "@"; type = "A"; value = "147.135.114.130"; ttl = 300; }
      { name = "@"; type = "MX"; priority = 10; target = "mail.neet.dev."; ttl = 14400; }
      { name = "@"; type = "TXT"; value = "\"v=spf1 include:mailgun.org mx -all\""; ttl = 3600; }
      { name = "_dmarc"; type = "TXT"; value = "\"v=DMARC1; p=none\""; ttl = 3600; }
      { name = "fry"; type = "A"; value = "100.117.73.96"; ttl = 3600; }
      { name = "git"; type = "CNAME"; target = "git.ponyo.neet.dev."; ttl = 3600; }
      { name = "irc"; type = "CNAME"; target = "irc.ponyo.neet.dev."; ttl = 3600; }
      { name = "krs._domainkey"; type = "TXT"; value = "\"k=rsa; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsu2Ev3WCXIMl4YefkeyurRLXlByTrsXKcREtXxHmFXxwwFx4V05o8aKiFFTgBjx1Q4HTVXpKJucUQaIftWfbm55WLRRpENDLnkmyqjaSLrijpE6Ytg46cziUgFrOtFq1qehns5tsUeo8CQ/J9a2zHK20iox51LMxQ7e0WZzUWfZWa/PeIwOVlrrAFvl0f7w8EHjUzEuAl+IYWvtFh4QPXKIxqwzQPIB9jEaRHUYFlK9LSMrfYPl9k0OjF/1xHMjzUkFZgcgfAoj4wtTDqYMXLV+bfJPbxLghSBZ7hshx3zqgqmMdOz6XdNSXI3/Pgd9p7clEdTki6ZEssXlJyS6LxwIDAQAB\""; ttl = 3600; }
      { name = "mail"; type = "A"; value = "147.135.114.130"; ttl = 30; }
      { name = "mail._domainkey"; type = "TXT"; value = "\"v=DKIM1; k=rsa; s=email; p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDnkeYFM9fTlRBihTQpPW+us7jBuFofKgvORRxm0dtyaumg4Z6ZWlol1DKZE2LJ196agh5agfkXkVm97x/LrZQRvS0822y42F86STee4+ZWdt9DV6j3zmucu1lqe70m0lB5PnnEqFi2r4SEpsii1ti+p38RAjeewQoLp/5A+7A59QIDAQAB\""; ttl = 3600; }
      { name = "ntfy"; type = "CNAME"; target = "ponyo.neet.dev."; ttl = 3600; }
      { name = "ponyo"; type = "CNAME"; target = "@"; ttl = 3600; }
      { name = "s0"; type = "A"; value = "100.112.73.53"; ttl = 3600; }
      { name = "status"; type = "CNAME"; target = "status.ponyo.neet.dev."; ttl = 3600; }
      { name = "tmp"; type = "CNAME"; target = "@"; ttl = 3600; }
      { name = "unlock.ponyo"; type = "CNAME"; target = "ponyo.neet.dev."; ttl = 3600; }
    ];
  };
  "neet.space" = {
    nameservers = [ "ns1.digitalocean.com." "ns2.digitalocean.com." "ns3.digitalocean.com." ];
    records = [
      { name = "@"; type = "A"; value = "100.76.85.13"; ttl = 300; }
      { name = "@"; type = "MX"; priority = 10; target = "mail.neet.dev"; ttl = 14400; }
      { name = "@"; type = "TXT"; value = "\"rizon_vhost=Googlebot,Zuckerberg,dailybot\""; ttl = 3600; }
      { name = "@"; type = "TXT"; value = "\"v=spf1 include:mailgun.org mx -all\""; ttl = 3600; }
      { name = "_dmarc"; type = "TXT"; value = "\"v=DMARC1; p=none\""; ttl = 3600; }
      { name = "chat"; type = "A"; value = "100.76.85.13"; ttl = 300; }
      { name = "mail._domainkey"; type = "TXT"; value = "\"v=DKIM1; k=rsa; s=email; p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCfsgdL8ngVtMFLdkTxaKfcO4zl2tWye9Dc6goDcKaGWadp4G/e4282fQ+jqG8aFYpGUrdq1yH3LhowA/mQuCr/WRWxsRatB4D0tTcQUSYAzduOuFWKfO029MdRxEGxt38c+lQjeck5+ScLTMo4CFhlaBT8syqcjLu4ORdwMCREmwIDAQAB\""; ttl = 3600; }
      { name = "smtp._domainkey"; type = "TXT"; value = "\"k=rsa; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAoI62Pb0vhm72bd67mZmNH+hwImJaHWirYO2iEedt4l2ESFVZ+3OZ5L33MnN/HT0h7WI4jSvG8lJz0y0WhXCA8TLrk5exa4kLz4bJEbW37yRO8FNgtU5CPQFtrXU94Dg6u+8DJJ9V+xFc4ufsvDgMffH9fRHXll9rDsrW2ae0+MhPSqIKMLWp/v108zXyDPBPNw5bPBxg48AQBv0y+21YAhFkAUdSm46JVZXMTEBzz/iLr3wvnX/QadnXn+0fUIGGvLT9dUQFZ6uYpRGOqRvIMtwKxdoCUyqLIMff5WB5yYhyVDftKrPAFwry93RT55U7zCnrBBznCefKeeQ+vjkTQQIDAQAB\""; ttl = 3600; }
      { name = "turn"; type = "CNAME"; target = "@"; ttl = 3600; }
    ];
  };
  "runyan.org" = {
    nameservers = [ "ns1.digitalocean.com." "ns2.digitalocean.com." "ns3.digitalocean.com." ];
    records = [
      { name = "@"; type = "A"; value = "100.76.85.13"; ttl = 300; }
      { name = "@"; type = "MX"; priority = 10; target = "mail.neet.dev"; ttl = 14400; }
      { name = "@"; type = "TXT"; value = "\"v=spf1 include:mailgun.org mx -all\""; ttl = 3600; }
      { name = "_dmarc"; type = "TXT"; value = "\"v=DMARC1; p=none\""; ttl = 3600; }
      { name = "collabora"; type = "CNAME"; target = "collabora.ponyo.neet.dev"; ttl = 3600; }
      { name = "mail._domainkey"; type = "TXT"; value = "\"v=DKIM1; k=rsa; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAt1N9lHlFuMHABaDrJJkAiyhbpH5WhXd2s3bJ+UF1CTqOYGr3dtXwnxEZCjXhv5QkGAbI60cD+YjNejRcMByn+R6FUhZp83eLxlPJej//N+oP5JSNp2irJEm0Qzx3Te7Qx9rtyrIFfNnpMSwGblmBVaONR7lbpJEYtoY34y5THlBA2DA9aHS48ybAfnw69LFev34Yr0i8ozIssbhsSqSsZOEJifQk5I0GQoskBCdfxQ4NfP6iuuj9HX8tkYGSdmdO3LaVWh/tRNAX451RHSLMhnQMHsGWBLJoA1eHBplQqYXpA2gRGwCcRDQZ5/D7Y3+8mvp2YgBlKG1Pav1QLrmPTwIDAQAB\""; ttl = 3600; }
      { name = "smtp._domainkey"; type = "TXT"; value = "\"k=rsa; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuAK0ydDLErw0gzn3bmyIU3urTrNuIkCWrmfl1DXWItmB8jM517uFERhOtoocnbhO4Y1+FvxU+YUhlZKfUccKEqtMjc/dROXOHX2nDRtchd1ss/fUOiwSOlRrZZexdunPs78mibrH6yUVyktGq+is6zpxNpyFbJE9LjScYDWw+reR+7oMrmPQnX3MJ15B1yXHuwkLvz2OWr7Kz2P6MzzlLNMT4haCFCBkcYwdLFGFNtNO5Lw33Azx8HmGnEd7BjT8Z/ZVRgv8YLZcczTCkdwbrFtDkv06xOr/5NXnYQKoUxS1jSOkGwkNHnYlJwedBYNDAkbUAGcGQ4SadUxQm6xpXwIDAQAB\""; ttl = 3600; }
      { name = "whiteboard"; type = "CNAME"; target = "whiteboard.ponyo.neet.dev"; ttl = 3600; }
    ];
  };
  "runyan.rocks" = {
    nameservers = [ "ns1.digitalocean.com." "ns2.digitalocean.com." "ns3.digitalocean.com." ];
    records = [
      { name = "@"; type = "A"; value = "147.135.114.130"; ttl = 300; }
      { name = "@"; type = "AAAA"; value = "2604:2dc0:101:200::1092"; ttl = 300; }
      { name = "@"; type = "MX"; priority = 10; target = "mail.neet.dev"; ttl = 14400; }
      { name = "@"; type = "TXT"; value = "\"v=spf1 include:mailgun.org mx -all\""; ttl = 3600; }
      { name = "_dmarc"; type = "TXT"; value = "\"v=DMARC1; p=none\""; ttl = 3600; }
      { name = "k1._domainkey"; type = "TXT"; value = "\"k=rsa; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAolNaBvjQPi92OJev5FIL2gSXPuDW3IFoKoUo+eksfZstT3F5LDxhqP2NpjiJQ02BM2fFz8BUYIknNC1saHO65Wc6htEnFXAwvpfamm8XXpfysBEjGDOnxpepGrN065Nlyz5XYPapQFC02YLU5l4+A/KJTDPShHMKs32ZCKmZ2YboeWsEt4TQK0mLH3I+9DZ/59yTr2u/mxzq3scMTHtFQXm17StFumVGZYsfuZIkQCBN64F+okxiS9X9FL0FF0YzktTTiz0H87XZG1IK6MF4GBgW0Jz9A4fWPUqrJFBC6FcPOJLw47o555FqcysqFal3QQATPwuxDKHfkWrcxI3AkQIDAQAB\""; ttl = 3600; }
      { name = "mail._domainkey"; type = "TXT"; value = "\"v=DKIM1; k=rsa; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA5dDZZfWWJ9C0HB9LXZT86yf8oo5x6wnTUECsbFduvozPBiwR2Li63XXr0WTx4BbjHTghe5z+6EyxMgJngWHUS+q9gkAFaJVm+jbuP7PvVkHt9/RKenPs6Sxyn3lqk263cxJ18Z1aWICgovBDuaXiC6FWv2z2P7A1V6VA/WbRGZA3QGRTK3qF9IN+WBaqUKIp0ZcLVdhMNeGmAq+Ot4+pqu8GL0M8S7E+AmUriuCcR/BCwP1iWdtu2ryq0iR3cdT+0nBuSwiueWnJxuAZbrzq0mIw8g9LVaeGFmzvhbKA5zIWSDiGRE3oiq2CQ3iWpuayb5Iy6BexfvLJadchREzd6QIDAQAB\""; ttl = 3600; }
    ];
  };
  "tar.ninja" = {
    nameservers = [ "ns1.digitalocean.com." "ns2.digitalocean.com." "ns3.digitalocean.com." ];
    records = [
      { name = "@"; type = "A"; value = "147.135.114.130"; ttl = 300; }
      { name = "@"; type = "AAAA"; value = "2604:2dc0:101:200::1092"; ttl = 300; }
      { name = "@"; type = "MX"; priority = 10; target = "mail.neet.dev"; ttl = 14400; }
      { name = "@"; type = "TXT"; value = "\"v=spf1 include:mailgun.org mx -all\""; ttl = 3600; }
      { name = "_dmarc"; type = "TXT"; value = "\"v=DMARC1; p=none\""; ttl = 3600; }
      { name = "bun-verify"; type = "TXT"; value = "1dd930257612a70a6fc600326cbe3903848dc2bc19a4dda39606d7aab201a85c"; ttl = 3600; }
      { name = "mail._domainkey"; type = "TXT"; value = "\"v=DKIM1; k=rsa; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA43EOZqcsaNWFTokyXZjniwiHqNovuXjjpklkCFSw0DiqNE1ZAI+9khO1cWDzEJLESvLkiO+AdeL+3BluEc8mtGcEa7CVzPsRQxQ6ABidyCtL5asDHtACmUz1wZG+5tbECXLmbuKafVVA7wY3FTJqwwLMk7Dm2njmXdD5YRxDFvnR1eQeKgPxzmBc7yhd+RsZElVvAYdGf8llvqsdRitV/oPrxCiNqQMvS/EdiAhegNyTBUtvSnv7HCo6A32V6/twOMjTMlqEq8zUOiJHTkH6jBLkRFcY7U0EonSharz7FR9iIKcrcxm6PggDRXYgErQQfv1LmAWlKOD7SOFX9S0PAwIDAQAB\""; ttl = 3600; }
      { name = "mailo._domainkey"; type = "TXT"; value = "\"k=rsa; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAp/lXoClCYyegOhvQXiKv/WWYH9M2k6l4/UrfprAyZ+waeEDzWb2bNjFmlZJkxq0VTys8t2kag1HppS7I/+FZWKgWEAsv8mhCeEyDUQOR98Gj4oIefh7Y+8ql3++D/tKKzPJWIFhOlo5TcETx+jL9hm1G45OvDmTYgbju/tdBq/yq0FQDJ+0kdWzFtYPoPSmLrcik2C17CkyMD33wiJmOCxKwddesscNHPLr095rEJ2XXiYJg9rHJhlxYmu3u09SuwDuk/UT1Y8DhvZNHRpMv+vsS+xCFpJU9kNSNtUU40XSxMi3HWCUaetTJlZQodr7d+nNqLF/PLjJvS1Lc/d1g1wIDAQAB\""; ttl = 3600; }
    ];
  };
  "thunderhex.com" = {
    nameservers = [ "ns1.digitalocean.com." "ns2.digitalocean.com." "ns3.digitalocean.com." ];
    records = [
      { name = "@"; type = "A"; value = "147.135.114.130"; ttl = 300; }
      { name = "@"; type = "AAAA"; value = "2604:2dc0:101:200::1092"; ttl = 300; }
      { name = "@"; type = "MX"; priority = 10; target = "mail.neet.dev"; ttl = 14400; }
      { name = "@"; type = "TXT"; value = "\"v=spf1 include:mailgun.org mx -all\""; ttl = 3600; }
      { name = "_dmarc"; type = "TXT"; value = "\"v=DMARC1; p=none\""; ttl = 3600; }
      { name = "k1._domainkey"; type = "TXT"; value = "\"k=rsa; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAohWXVoGp9x1f7TFfxdp4p6VwANxvsrZGZmq4Tfuib9us+ADzePU9rQFRnWjqvteu/U800KMP/7+krQSvb2x9MpVmHs+T4nbRwGowVAmgVJR4LhaipTIDTVDqXhg5/1NVeRr6AFfqOsw7jI2ubinGqiu3cmXjWHryvJEVF63Iio5ckL9zO4A23Av1YeABDh8bzDs7HQ6l2yhUMsHy4vaZ9AijALWUg2NilLMovXkFy32qhLNza+vjJ9wE7Q+3H/Tb3L5JRgKyOAYye3o8mwnsXTh/I/nW+AxK5ixANg+nC4hNeI3fuXaL7vEqgNzxoRyF5H90FjHfN707XR2YvQyc/wIDAQAB\""; ttl = 3600; }
      { name = "mail._domainkey"; type = "TXT"; value = "\"v=DKIM1; k=rsa; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA3trwBpGv/mpss4Ep2fXpGlZju4zahfaBF2pFEmqZcgdvPeYiDPKHyRUV8BZ+socO1Qj0M6Rwn09NRBrWksVGfIQdP3nT/DU+Le3zEIT0Tbjdx1Ag//E3Z7gnreEoUkcF18Lsghitlnd0XX1tnLmmta09tpgHi06AZyFjsGzN0mBOGkpoTAKd991VT4FyR6p2YvvWBhmgptAYlWJAIM44v+zV5GXUH37mMBwGGAk8/N+CWiuqUsJriyv/qOBb/rZgUPw/bgJSwJ4H0eU3btnZocv5D3d3iKVCl8YfmW7JM6Fev5S+JAOYufIiyvQisR6Hm9zm2GVQZDdiP2uHbZvu4wIDAQAB\""; ttl = 3600; }
    ];
  };
  "zstd.zip" = {
    nameservers = [ "ns1.digitalocean.com." "ns2.digitalocean.com." "ns3.digitalocean.com." ];
    records = [
      { name = "@"; type = "A"; value = "147.135.114.130"; ttl = 300; }
      { name = "@"; type = "AAAA"; value = "2604:2dc0:101:200::1092"; ttl = 300; }
      { name = "@"; type = "MX"; priority = 10; target = "mail.neet.dev"; ttl = 14400; }
      { name = "@"; type = "TXT"; value = "\"v=spf1 include:mailgun.org mx -all\""; ttl = 3600; }
      { name = "_dmarc"; type = "TXT"; value = "\"v=DMARC1; p=none\""; ttl = 3600; }
    ];
  };
}
