name: Check Flake

on: [push]

env:
  DEBIAN_FRONTEND: noninteractive
  PATH: /run/current-system/sw/bin/

jobs:
  check-flake:
    runs-on: nixos
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: |
          pwd
          ls -lah .
          whoami

      - name: Check Flake
        run: nix flake check --show-trace