name: Check Flake

on: [push]

env:
  DEBIAN_FRONTEND: noninteractive
  PATH: /run/current-system/sw/bin/

jobs:
  check-flake:
    runs-on: nixos
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: attic -V

      - name: Setup Attic Cache
        uses: https://git.neet.dev/zuckerberg/attic-action@main
        with:
          endpoint: ${{ secrets.ATTIC_ENDPOINT }}
          cache: ${{ secrets.ATTIC_CACHE }}
          token: ${{ secrets.ATTIC_TOKEN }}

      - name: Check Flake
        run: nix flake check --all-systems --print-build-logs --log-format raw --show-trace