name: Check Flake

on: [push]

env:
  DEBIAN_FRONTEND: noninteractive
  PATH: /run/current-system/sw/bin/
  XDG_CONFIG_HOME: ${{ runner.temp }}/.config
  ATTIC_ENDPOINT: ${{ vars.ATTIC_ENDPOINT }}
  ATTIC_TOKEN: ${{ secrets.ATTIC_TOKEN }}

jobs:
  check-flake:
    runs-on: nixos
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build and cache
        run: bash .gitea/scripts/build-and-cache.sh

      - name: Notify on failure
        if: failure()
        run: |
          curl -s \
            -H "Authorization: Bearer ${{ secrets.NTFY_TOKEN }}" \
            -H "Title: Flake check failed" \
            -H "Priority: high" \
            -H "Tags: warning" \
            -d "Check failed for ${{ gitea.ref_name }}. Check: ${{ gitea.server_url }}/${{ gitea.repository }}/actions/runs/${{ gitea.run_number }}" \
            https://ntfy.neet.dev/nix-flake-updates
