name: Sync Tailscale ACL

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch: {}

jobs:
  sync-tailscale-acl:
    runs-on: nixos
    env:
      TAILSCALE_OAUTH_CLIENT_ID: ${{ secrets.TAILSCALE_OAUTH_CLIENT_ID }}
      TAILSCALE_OAUTH_SECRET: ${{ secrets.TAILSCALE_OAUTH_SECRET }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Test checked-in Tailscale ACL
        if: github.event_name == 'pull_request' && env.TAILSCALE_OAUTH_CLIENT_ID != '' && env.TAILSCALE_OAUTH_SECRET != ''
        uses: tailscale/gitops-acl-action@v1
        with:
          oauth-client-id: ${{ env.TAILSCALE_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ env.TAILSCALE_OAUTH_SECRET }}
          tailnet: koi-bebop.ts.net
          policy-file: common/network/tailscale-acl.hujson
          action: test

      - name: Apply checked-in Tailscale ACL
        if: (github.event_name == 'push' || github.event_name == 'workflow_dispatch') && env.TAILSCALE_OAUTH_CLIENT_ID != '' && env.TAILSCALE_OAUTH_SECRET != ''
        uses: tailscale/gitops-acl-action@v1
        with:
          oauth-client-id: ${{ env.TAILSCALE_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ env.TAILSCALE_OAUTH_SECRET }}
          tailnet: koi-bebop.ts.net
          policy-file: common/network/tailscale-acl.hujson
          action: apply
