name: Sync Tailscale ACL

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch: {}

jobs:
  sync-tailscale-acl:
    runs-on: nixos
    env:
      TAILSCALE_API_KEY: ${{ secrets.TAILSCALE_API_KEY }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Test checked-in Tailscale ACL
        if: github.event_name == 'pull_request' && env.TAILSCALE_API_KEY != ''
        uses: tailscale/gitops-acl-action@v1
        with:
          api-key: ${{ env.TAILSCALE_API_KEY }}
          tailnet: koi-bebop.ts.net
          policy-file: common/network/tailscale-acl.hujson
          action: test

      - name: Apply checked-in Tailscale ACL
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        uses: tailscale/gitops-acl-action@v1
        with:
          api-key: ${{ env.TAILSCALE_API_KEY }}
          tailnet: koi-bebop.ts.net
          policy-file: common/network/tailscale-acl.hujson
          action: apply
